imports:
    - { resource: "grid/services.yml" }
    - { resource: "ajaxgrid/services.yml" }    
    - { resource: "menu/services.yml" }    
    - { resource: "filterable_menu/services.yml" }    
    
parameters:
    twig.extension.bluegrass.blues.widget.class: Bluegrass\Blues\Bridge\Twig\Extension\Widget\WidgetExtension  
    
services:
  
    twig.extension.bluegrass.blues.widget:
        class: %twig.extension.bluegrass.blues.widget.class%
        arguments:     []
        tags:
            - { name: twig.extension }
            
            